// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Canvas, CanvasData, CanvasTableId } from "./tables/Canvas.sol";
import { Rewards, RewardsTableId } from "./tables/Rewards.sol";
import { PeriodRewardTotal, PeriodRewardTotalTableId } from "./tables/PeriodRewardTotal.sol";
import { Lock, LockTableId } from "./tables/Lock.sol";
import { InitialBlock, InitialBlockTableId } from "./tables/InitialBlock.sol";
import { CanvasColor, CanvasColorData, CanvasColorTableId } from "./tables/CanvasColor.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { RewardClaim, RewardClaimTableId } from "./tables/RewardClaim.sol";
import { Spent, SpentData, SpentTableId } from "./tables/Spent.sol";
